version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: toolset
    binary: toolset
    main: ./cmd/toolset
    ldflags:
      - -s
      - -w
      - -X github.com/kazhuravlev/toolset/internal/toolversion.version={{.Summary}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

brews:
  - name: toolset
    goarm: "6"
    goamd64: v3
    repository:
      owner: kazhuravlev
      name: homebrew-toolset
      branch: master
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/kazhuravlev/toolset/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: kazhuravlev+goreleaserbot@fastmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/kazhuravlev/toolset"
    description: "Toolset helps to keep a project-specific tools"
    license: "MIT"
    test: |
      system "#{bin}/toolset help"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
