version: '3'

vars:
  TOOLSET: go run ../cmd/toolset

tasks:
  tools:install:
    desc: Install tools
    run: once
    cmds:
      - echo ">> Install tools..."
      - go run github.com/kazhuravlev/toolset/cmd/toolset@latest sync

  fmt:
    desc: Format codebase
    deps:
      - "tools:install"
    vars:
      GO_FILES:
        sh: "find . -type f -name '*.go' -not -path './internal/version/*' | xargs echo"
    cmds:
      - echo ">>> Format code..."
      - go fmt ./...
      - toolset run gofumpt -l -w {{.GO_FILES}}
      - toolset run goimports -d -w {{.GO_FILES}}

  lint:
    desc: Run static analysis
    deps:
      - "tools:install"
    cmds:
      - echo ">> Run linter..."
      - toolset run golangci-lint run ./...

  tests:
    desc: Run project tests
    deps:
      - "tools:install"
    cmds:
      - echo ">> Run tests..."
      - toolset run gotestsum
      - task: "test:remove"
      - task: "test:alias"
      - task: "test:runtimes"
      - task: "test:ensure"
      - task: "test:ensure:gh"
      - task: "test:other"

  upd:dl:
    - rm -rf dl
    - git clone --depth 1 https://github.com/golang/dl.git
    - rm -rf internal/version
    - mv dl/internal/version internal/version
    - rm -rf dl
    - rm ./internal/version/gotip.go
    - go test ./internal/version

  init:
    dir: temp_tests
    cmds:
      - "rm .toolset.json .toolset.lock.json || true"
      - "{{.TOOLSET}} init --copy-from git+https://gist.github.com/c92c40d0e4329c1c2fe9372216474cd7.git:/formatters.json"

  test:remove:
    dir: temp_tests
    cmds:
      - task: "init"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} which goimports gofumpt"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} remove goimports gofumpt"
      - "{{.TOOLSET}} list"

  test:alias:
    dir: temp_tests
    cmds:
      - task: "init"
      - "{{.TOOLSET}} add go github.com/vburenin/ifacemaker hello"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} list | grep hello"

  test:runtimes:
    dir: temp_tests
    cmds:
      - "rm .toolset.json .toolset.lock.json || true"
      - "{{.TOOLSET}} init"
      - "{{.TOOLSET}} runtime add go@1.22.10"
      - "{{.TOOLSET}} runtime add go@1.24"
      - "{{.TOOLSET}} runtime add go@1.25"
      - "{{.TOOLSET}} runtime add go"
      - "{{.TOOLSET}} runtime add gh"
      - "{{.TOOLSET}} runtime list"
      - "{{.TOOLSET}} ensure go@1.25 golang.org/x/tools/cmd/goimports"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} remove goimports"
      - "{{.TOOLSET}} ensure go@1.24 golang.org/x/tools/cmd/goimports"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} remove goimports"
      - "{{.TOOLSET}} list"

  test:ensure:
    dir: temp_tests
    cmds:
      - "rm .toolset.json .toolset.lock.json || true"
      - "{{.TOOLSET}} init ."
      - "{{.TOOLSET}} ensure go@1.25.0 golang.org/x/tools/cmd/goimports@v0.37.0"
      - "{{.TOOLSET}} ensure go@1.25.0 mvdan.cc/gofumpt@v0.9.1"
      - "{{.TOOLSET}} ensure go@1.25.0 github.com/bufbuild/buf/cmd/buf@v1.57.2"
      - "{{.TOOLSET}} ensure go@1.25.0 github.com/go-delve/delve/cmd/dlv@v1.25.2"
      - "{{.TOOLSET}} ensure go@1.25.0 github.com/go-swagger/go-swagger/cmd/swagger@v0.32.3"
      - "{{.TOOLSET}} ensure go@1.25.0 github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8"
      - "{{.TOOLSET}} ensure go@1.25.0 github.com/goreleaser/goreleaser/v2@v2.12.5"
      - "{{.TOOLSET}} ensure go@1.25.0 github.com/kisielk/errcheck@v1.9.0"
      - "{{.TOOLSET}} ensure go@1.25.0 github.com/mgechev/revive@v1.12.0"
      - "{{.TOOLSET}} ensure go@1.25.0 github.com/segmentio/golines@v0.13.0"
      - "{{.TOOLSET}} ensure go@1.25.0 honnef.co/go/tools/cmd/staticcheck@v0.6.1"
      - "{{.TOOLSET}} ensure go@1.25.0 github.com/kazhuravlev/git-tools/cmd/gt@v0.12.2"

  test:ensure:gh:
    dir: temp_tests
    cmds:
      - "rm .toolset.json .toolset.lock.json || true"
      - "{{.TOOLSET}} init ."
      - "{{.TOOLSET}} ensure gh golangci/golangci-lint@v2.3.0"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} ensure gh golangci/golangci-lint@v2.4.0"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} ensure gh golangci/golangci-lint@v2.5.0"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} run golangci-lint version"

  test:other:
    dir: temp_tests
    cmds:
      - task: "init"
      - "{{.TOOLSET}} runtime add go@1.24.0"
      - "{{.TOOLSET}} runtime add go@1.25.0"
      - "{{.TOOLSET}} runtime add go@1.25.1"
      - "{{.TOOLSET}} runtime add go@1.23.0"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} ensure -tags x1 go@1.25.0 golang.org/x/tools/cmd/goimports@v0.25.0"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} ensure -tags x2 go@1.25.0 golang.org/x/tools/cmd/goimports@v0.24.0"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} ensure -tags x3 go@1.24.0 golang.org/x/tools/cmd/goimports@v0.23.0"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} ensure -tags x4 go golang.org/x/tools/cmd/goimports@v0.25.0"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} add -tags group1 go@1.25.1 golang.org/x/tools/cmd/goimports@v0.24.0"
      - "{{.TOOLSET}} add go@1.25.1 golang.org/x/tools/cmd/goimports"
      - "{{.TOOLSET}} add go@1.25.1 golang.org/x/tools/cmd/goimports@latest"
      - "{{.TOOLSET}} add go@1.25.1 github.com/bufbuild/buf/cmd/buf@v1.47.2"
      - "{{.TOOLSET}} add go@1.25.1 github.com/go-delve/delve/cmd/dlv@latest"
      - "{{.TOOLSET}} add go@1.23.0 github.com/go-swagger/go-swagger/cmd/swagger@latest"
      - "{{.TOOLSET}} add go@1.25.1 github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.0"
      - "{{.TOOLSET}} add go@1.25.1 github.com/goreleaser/goreleaser/v2@latest"
      - "{{.TOOLSET}} add go@1.25.1 github.com/kisielk/errcheck@latest"
      - "{{.TOOLSET}} add --tags group1 go github.com/mgechev/revive@latest"
      - "{{.TOOLSET}} add --tags group1 go github.com/segmentio/golines@latest"
      - "{{.TOOLSET}} add --tags group1 go honnef.co/go/tools/cmd/staticcheck@2022.1"
      - "{{.TOOLSET}} sync --tags group1"
      - "{{.TOOLSET}} add --tags formatter,ci go golang.org/x/tools/cmd/goimports@v0.21.0"
      - "{{.TOOLSET}} add --tags local,ci go github.com/kazhuravlev/git-tools/cmd/gt"
      - "{{.TOOLSET}} add --tags local,ci,linters go github.com/golangci/golangci-lint/cmd/golangci-lint@v1.60.2"
#      - "{{.TOOLSET}} upgrade --tags linters"
      - "{{.TOOLSET}} add --tags formatters --copy-from git+https://gist.github.com/c92c40d0e4329c1c2fe9372216474cd7.git:/formatters.json"
      - "{{.TOOLSET}} add --tags codegen --include git+ssh://git@gist.github.com:c92c40d0e4329c1c2fe9372216474cd7.git:/codegen.json"
      - "{{.TOOLSET}} add --tags formatters --include git+https://gist.github.com/c92c40d0e4329c1c2fe9372216474cd7.git:/formatters.json"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} sync --tags codegen"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} which buf gt dlv"
      - "{{.TOOLSET}} upgrade"
      - "{{.TOOLSET}} sync"
      - "{{.TOOLSET}} run gt tag last"
      - "{{.TOOLSET}} list"
      - "{{.TOOLSET}} run buf --version"
      - "{{.TOOLSET}} run dlv version"
      - "{{.TOOLSET}} run swagger version"
      - "{{.TOOLSET}} run golangci-lint version"
      - "{{.TOOLSET}} run goreleaser --version"
      - "{{.TOOLSET}} run revive --version"
      - "{{.TOOLSET}} run golines --version"
      - "{{.TOOLSET}} run staticcheck -version"
      - "{{.TOOLSET}} run gt --version"
      - "{{.TOOLSET}} run gofumpt --version"
      - "{{.TOOLSET}} list"
